# Main configuration

# Compatible mode for other plugins like HealthBar, ColoredTags, GhostPlayer, McCombatLevel, etc. ......
# or the vanilla scoreboard
# In case you miss the log message: this option requires the plugin called ProtocolLib
# This option will work around the Bukkit API and will send raw packets
compatibilityMode: false

# Should be the node disabled-worlds handled as whitelist or blacklist
disabled-worlds-whitelist: false

disabled-worlds:
  - city

Scoreboard:
  Title: '&a&lStats'
  # seconds
  # For instant updates you can or 1 and it will update every second
  Update-delay: 2
  Items:
    # The Title must have under 48 characters
    # Title: Type
    '&9Online': '%online%'
    '&9Money': '%money%'
    # Your can choose your custom score here
    '&aHello World': 1337

# Let ScoreboardStats track stats (kills, deaths, mobkills, killstreak) You need no plugin for this
enable-pvpstats: false

Temp-Scoreboard-enabled: false

Temp-Scoreboard:
  Title: '&a&lTop Kills'
  # %mob% | %kills% | %killstreak%
  Type: '%kills%'
  Color: '&9'
  # How many Players would be displayed
  Items: 5
  Intervall-show: 300
  Intervall-disappear: 300
